# Files the IDAPython build copies from pywraps/ and deploys from examples/.

set(IDAPYTHON_PYWRAPS
    py_bytes.hpp
    py_bytes.py
    py_bytes_custdata.hpp
    py_bytes_custdata.py
    py_bytes_find_bytes.hpp
    py_bytes_find_bytes.py
    py_dbg.hpp
    py_dbg.py
    py_diskio.hpp
    py_expr.hpp
    py_expr.py
    py_fixup.py
    py_fpro.hpp
    py_fpro_end.py
    py_frame.hpp
    py_frame.py
    py_funcs.hpp
    py_funcs.py
    py_gdl.py
    py_graph.hpp
    py_graph.py
    py_hexrays.hpp
    py_hexrays.py
    py_hexrays_hooks.hpp
    py_ida.py
    py_idaapi.hpp
    py_idaapi.py
    py_idaapi_loader_input.hpp
    py_idc.hpp
    py_idd.hpp
    py_idd.py
    py_idp.hpp
    py_idp.py
    py_idp_idbhooks.hpp
    py_idp_idbhooks.py
    py_idp_notify_when.py
    py_ieee.hpp
    py_ieee.py
    py_kernwin.hpp
    py_kernwin.py
    py_kernwin_askform.hpp
    py_kernwin_askform.py
    py_kernwin_choose.hpp
    py_kernwin_choose.py
    py_kernwin_cli.hpp
    py_kernwin_cli.py
    py_kernwin_custview.hpp
    py_kernwin_custview.py
    py_kernwin_end.py
    py_kernwin_idaview.hpp
    py_kernwin_idaview.py
    py_kernwin_plgform.hpp
    py_kernwin_plgform.py
    py_kernwin_viewhooks.hpp
    py_kernwin_viewhooks.py
    py_lines.hpp
    py_lines.py
    py_loader.hpp
    py_lumina.hpp
    py_lumina.py
    py_moves.hpp
    py_moves.py
    py_moves_end.py
    py_nalt.hpp
    py_nalt.py
    py_name.hpp
    py_name.py
    py_netnode_end.py
    py_pro.hpp
    py_pro.py
    py_range.hpp
    py_range.py
    py_registry.hpp
    py_search.hpp
    py_search.py
    py_segment.hpp
    py_segment.py
    py_segregs.py
    py_typeinf.hpp
    py_typeinf.py
    py_typeinf_custom_callcnv.hpp
    py_ua.hpp
    py_ua.py
    py_xref.hpp
    py_xref.py
    pywraps.hpp
)

set(IDAPYTHON_EXAMPLES
    README.md
    debugger/appcall/simple_appcall_common.py
    debugger/appcall/simple_appcall_linux.py
    debugger/appcall/simple_appcall_win.py
    debugger/dbghooks/automatic_steps.py
    debugger/dbghooks/dbg_trace.py
    debugger/misc/print_call_stack.py
    debugger/misc/print_registers.py
    debugger/misc/registers_context_menu.py
    debugger/show_debug_names.py
    decompiler/colorize_pseudocode_lines.py
    decompiler/curpos_details.py
    decompiler/decompile_entry_points.py
    decompiler/produce_c_file.py
    decompiler/serialize.py
    decompiler/serialize_minsn.py
    decompiler/vds1.py
    decompiler/vds10.py
    decompiler/vds11.py
    decompiler/vds12.py
    decompiler/vds13.py
    decompiler/vds17.py
    decompiler/vds19.py
    decompiler/vds21.py
    decompiler/vds3.py
    decompiler/vds4.py
    decompiler/vds5.py
    decompiler/vds6.py
    decompiler/vds7.py
    decompiler/vds8.py
    decompiler/vds_create_hint.py
    decompiler/vds_hooks.py
    decompiler/vds_modify_user_lvars.py
    decompiler/vds_xrefs.py
    disassembler/add_frame_member.py
    disassembler/ana_emu_out.py
    disassembler/assemble.py
    disassembler/custom_data_types_and_formats.py
    disassembler/dscu_query.py
    disassembler/dump_extra_comments.py
    disassembler/dump_flowchart.py
    disassembler/dump_flowchart_ea.py
    disassembler/dump_func_info.py
    disassembler/dump_line_sections.py
    disassembler/extract_macho_image.py
    disassembler/find_string.py
    disassembler/func_ti_changed_listener.py
    disassembler/indexer_substring_search.py
    disassembler/install_user_defined_prefix.py
    disassembler/list_bookmarks.py
    disassembler/list_function_items.py
    disassembler/list_imports.py
    disassembler/list_patched_bytes.py
    disassembler/list_problems.py
    disassembler/list_segment_functions.py
    disassembler/list_segment_functions_using_idautils.py
    disassembler/list_strings.py
    disassembler/list_struct_accesses.py
    disassembler/log_idb_events.py
    disassembler/log_idp_events.py
    disassembler/operand_changed.py
    disassembler/produce_lst_file.py
    disassembler/replay_prototypes_changes.py
    index.md
    misc/cvt64/py_cvt64_sample.py
    misc/extend_idc.py
    misc/extract_addr_from_tagged_line.py
    misc/idapythonrc.py
    misc/merge/py_mex1.py
    misc/merge/py_mex3.py
    misc/print_license_info.py
    templates/README.md
    templates/document.py
    templates/interactive.py
    templates/snippet.py
    types/apply_callee_tinfo.py
    types/change_stkvar_name.py
    types/change_stkvar_type.py
    types/create_array.py
    types/create_bfstruct.py
    types/create_bmenum.py
    types/create_libssh2_til.py
    types/create_struct_by_member.py
    types/create_struct_by_parsing.py
    types/create_structure_programmatically.py
    types/create_union_by_member.py
    types/create_user_shared_data.py
    types/custom_calling_convention.py
    types/del_struct_members.py
    types/gap_size_align_snippet.py
    types/get_best_fit_member.py
    types/get_innermost_member.py
    types/import_type_from_til.py
    types/insert_struct_member.py
    types/list_enum_member.py
    types/list_frame_info.py
    types/list_func_details.py
    types/list_stkvar_xrefs.py
    types/list_struct_member.py
    types/list_struct_xrefs.py
    types/list_union_member.py
    types/mark_func_spoiled.py
    types/modify_struct_member.py
    types/operand_to_field_path.py
    types/operand_to_struct_member.py
    types/print_stkvar_xrefs.py
    types/setpehdr.py
    types/visit_tinfo.py
    ui/actions.py
    ui/add_hotkey.py
    ui/auto_instantiate_widget_plugin.py
    ui/colorize_disassembly.py
    ui/colorize_disassembly_on_the_fly.py
    ui/custom_cli.py
    ui/dump_selection.py
    ui/forms/askusingform.py
    ui/graphs/custom_graph_with_actions.py
    ui/graphs/sync_two_graphs.py
    ui/idaview/wrap_idaview.py
    ui/listings/custom_viewer.py
    ui/listings/jump_next_comment.py
    ui/listings/save_and_restore_listing_pos.py
    ui/misc/add_menus.py
    ui/open_ida_link.py
    ui/pyqt/inject_command.py
    ui/pyqt/paint_over_graph.py
    ui/pyqt/paint_over_navbar.py
    ui/pyqt/populate_pluginform_with_pyqt_widgets.py
    ui/register_timer.py
    ui/tabular_views/custom/choose.py
    ui/tabular_views/custom/choose_multi.py
    ui/tabular_views/custom/choose_with_checkboxes.py
    ui/tabular_views/custom/func_chooser.py
    ui/tabular_views/string_window/show_selected_strings.py
    ui/trigger_actions_programmatically.py
    ui/uihooks/func_chooser_coloring.py
    ui/uihooks/lines_rendering.py
    ui/uihooks/log_misc_events.py
    ui/uihooks/prevent_jump.py
    ui/waitbox/show_and_hide_waitbox.py
)
